call_method:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "playlist"
      selector:
        text:
    parameters:
      status: secondary
      example: '["loadtracks", "album.titlesearch=Revolver"]'
      selector:
        object:
call_query:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "albums"
      selector:
        text:
    parameters:
      status: secondary
      example: '["0", "20", "search:Revolver"]'
      selector:
        object:
sync:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    other_player:
      required: true
      example: "media_player.living_room"
      selector:
        text:
unsync:
  target:
    entity:
      integration: squeezebox
      domain: media_player
